# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'hack418' do
	pod 'Alamofire','~> 2.0'
	pod 'SwiftyJSON'
	pod 'Spring'
end

target 'hack418Tests' do

end

target 'hack418UITests' do

end

